# iStat Menus
PROCESS-NAME,iStat Menus Menubar
PROCESS-NAME,iStat Menus Helper
PROCESS-NAME,com.bjango.istatmenus.daemon

DOMAIN,ip6.istatmenus.app
DOMAIN,ip4.istatmenus.app
DOMAIN,ip.istatmenus.app
DOMAIN-SUFFIX,istatmenus.app
