# ikuncode中转
DOMAIN-SUFFIX,ikuncode.cc
# codemirror 中转
DOMAIN-SUFFIX,codemirror.codes
# duckcoding.com 中转
DOMAIN-SUFFIX,duckcoding.com
DOMAIN-SUFFIX,duckcoding.ai
# packyapi.com
DOMAIN-SUFFIX,packyapi.com
# kuaipao.pro
DOMAIN-SUFFIX,kuaipao.pro
# ooioo.work
DOMAIN-SUFFIX,ooioo.work
# gateai.cc
DOMAIN-SUFFIX,gateai.cc